### ISSUE TITLE
Scaling the histogram matrix in WH.1d.PCA

### ISSUE THREAD

**Issue by diogo-almeida** [Airpino/HistDAWass#2]
Hi there,

I was trying to reproduce the analysis presented in Verde, Irpino, and Balzanella (2016) by coding it from scratch and comparing the results I was getting with the results I would get from using HistDAWass::WH.1d.PCA. 

I was able to reproduce the histograms that I would get by using HistDAWass::data2hist on my own.

I also know function HistDAWass::WH.1d.PCA calls FactoMineR::PCA to perform principal component analysis, so I used the same function on the same set of histograms.

This is where I got surprised: Even though I was using the same input data and the same PCA function, I got identical variable loadings (PCAout$var$cor), but different factor scores (PCAout$ind$coord) and variable principal coordinates (PCAout$var$coord). The only way this should be possible is if function HistDAWass::WH.1d.PCA does some internal scaling on the input data before it passes it to the PCA function.

Inspecting the source code of HistDAWass::WH.1d.PCA, I noticed that this is indeed the case. Apparently, the data matrix is scaled by the square root of the number of quantiles (if using deciles, that number would be 10+1). The code in the function is the following:

> MATQ/sqrt((quantiles + 1))

If I scale my data accordingly, I am able to precisely reproduce the results from HistDAWass::WH.1d.PCA. However, I was wondering what the purpose of this scaling choice is. I couldn't find any information about it on the paper or online. Any help understanding this would be greatly appreciated!

**Comment by Airpino** [comment]
Dear Diego,
now I am in vacation with my family. If you have a bit of patience I 
will answer more precisely when I'll be back at home.
Anyway, about your question I remember that

if M=MATQ/sqrt((quantiles + 1)) and being Mc the matrix centered for 
each comlumn

the trace of t(Mc)%*%Mc is an approximation of the variance of a 
distributional variable computed by using the Wasserstein metric.

Now, since the eigenvalues sum to the trace of the matrix t(Mc)%*%Mc, we 
can assume that each factorial axes decomposes the variance of the 
distributional variable at hand according to its proportion w.r.t. the 
trace.
See from formula (15) in the attached paper.
I hope to have clarified something, if not please fell free to ask me 
more details.

Antonio Irpino

Il 02/08/2017 19:11, Diogo Almeida ha scritto:

**Comment by diogo-almeida** [comment]
Thank you for your answer! I understand now the rationale behind the scaling choice.
